name: Android CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    
    env:
      MAPS_API_KEY: ${{ secrets.MAPS_API_KEY }}

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: gradle
        
    - name: Set API key placeholder
      run: sed -i 's/<MAPS_API_KEY>/$MAPS_API_KEY/' app/src/main/AndroidManifest.xml
    
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Run unit tests
      run: ./gradlew testDebugUnitTest -PmapsApiKey="$MAPS_API_KEY"
    
    - name: Build debug APK
      run: ./gradlew assembleDebug -PmapsApiKey="$MAPS_API_KEY"
    
    - name: Build release APK
      run: ./gradlew assembleRelease -PmapsApiKey="$MAPS_API_KEY"
